# Files in this directory include Claude Agent and command definitions
# which are prompts parsed by Claude Agents

# They inherit the basic linting rules as well as the common prompt rules
# These linting rules cascade to all folders in the .claude folder.

extends: ../.markdownlint-prompts.yaml
