name: Proofread PRs
on:
  pull_request_target:
    types:
      - opened
    paths:
      - '**.md'

jobs:
  proofread:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Proofread PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        with:
          direct_prompt: |
            Review the documentation changes in this pull request. Focus on spelling and grammar.
            Suggest improvements where appropriate.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
