name: Weekly Release Summary

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'

  # Allow manual triggering from GitHub Actions tab
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the release (e.g., v1.2.3)'
        required: true
      release_name:
        description: 'Name for the release'
        required: false

jobs:
  create-weekly-release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Generate tag name for scheduled run
        if: github.event_name == 'schedule'
        id: generate-tag
        run: |
          # Get current date in YYYY.MM.DD format
          CURRENT_DATE=$(date +"%Y.%m.%d")
          echo "RELEASE_TAG=v${CURRENT_DATE}" >> $GITHUB_ENV
          echo "RELEASE_NAME=Weekly Release ${CURRENT_DATE}" >> $GITHUB_ENV

      - name: Set manual release info
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${{ github.event.inputs.release_name || github.event.inputs.release_tag }}" >> $GITHUB_ENV

      - name: Create Release with Claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: /create-release ${{ env.RELEASE_TAG }} "${{ env.RELEASE_NAME }}"
          claude_args: |
            --model claude-3-5-sonnet-20241022
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
